[tool.poetry]
name = "krakenci-client"
version = "0.0"
description = "A client tool for Kraken CI server."
authors = ["Michal Nowikowski <godfryd@gmail.com>"]
readme = "README.md"
homepage = "https://kraken.ci/"
repository = "https://github.com/kraken-ci/kraken"
documentation = "https://kraken.ci/docs"
keywords = ["building", "testing", "continuous-integration", "ci", "cd", "cicd"]
license = "Apache-2.0"

classifiers = [
    "Topic :: Software Development",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Testing",
    "License :: OSI Approved :: Apache Software License"
]

packages = [
  { include = "kraken" },
]

include = ["kraken/client/*.py"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"
click = "^7.1.2"
tabulate = "^0.8.9"
distro = "^1.7.0"

[tool.poetry.scripts]
kkci = 'kraken.client.main:main'

[tool.poetry.dev-dependencies]
pylint = "2.13.9"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.core.masonry.api"
