images = {
  'bld-kraken'       => ['bld-kraken:20221115'],
  'bld-kraken-22.04' => ['bld-kraken-22.04:20231112'],

  'kraken-agent-base-22.04' => ['kraken-agent-base-22.04:20231111'],

  'centos'        => ['centos:8'],
  'fedora'        => ['fedora:33'],
  'ubuntu'        => ['ubuntu:20.04'],
  'ubuntu-22.04'  => ['ubuntu:22.04-20230121', 'ubuntu:22.04'],

  'clojure'       => ['clojure:1.11'],
  'crystal'       => ['crystal:1.4'],
  'dart'          => ['dart:2.16'],
  'elixir'        => ['elixir:1.13'],
  'erlang'        => ['erlang:23.3'],
  'gcc'           => ['gcc:11.3'],
  'go'            => ['golang:1.18.0', 'golang:1.18', 'golang:latest'],
  'groovy'        => ['groovy:3.0'],
  'haskell'       => ['haskell:9.2'],
  'haxe'          => ['haxe:4.2'],
  'julia'         => ['julia:1.7'],
  'mono'          => ['mono:6.12'],
  'node'          => ['node:18.0'],
  'openjdk'       => ['openjdk:11.0', 'openjdk:11'],
  'openjdk-17'    => ['openjdk:17.0', 'openjdk:17'],
  'perl'          => ['perl:5.34'],
  'php'           => ['php:8.0'],
  'python'        => ['python:3.8.5', 'python:3.8'],
  'python-3.11'   => ['python:3.11.1', 'python:3.11', 'python:3', 'python:latest'],
  'ruby'          => ['ruby:3.1'],
  'rakudo'        => ['rakudo:2021.04'],
  'rust'          => ['rust:1.60'],
  'swift'         => ['swift:5.6'],

  'mlflow'        => ['mlflow'],
}

all_blds = []
all_pushs = []
images.each do | name, tags |
  task "push-#{name}" do
    tags.each do | tag |
      sh "docker push krakenci/#{tag}"
    end
  end

  task "bld-#{name}" do
    dkr_file = "docker-#{name}.txt"
    main_tag = tags.shift
    sh "docker build -t krakenci/#{main_tag} -f #{dkr_file} ."
    tags.each do | tag |
      sh "docker tag krakenci/#{main_tag} krakenci/#{tag}"
    end
  end

  all_blds.append("bld-#{name}")
  all_pushs.append("push-#{name}")
end

task :bld_all => all_blds
task :push_all => all_pushs
