version: '3.6'

services:
  server:
    restart: always
    image: eu.gcr.io/kraken-261806/kkserver:kk_ver
    environment:
      - KRAKEN_REDIS_ADDR
      - KRAKEN_DB_URL
      - KRAKEN_LOGSTASH_PORT
      - KRAKEN_LOGSTASH_ADDR
      - KRAKEN_ELASTICSEARCH_PORT
      - KRAKEN_ELASTICSEARCH_URL
      - KRAKEN_SERVER_PORT
      - KRAKEN_SERVER_ADDR
      - KRAKEN_PLANNER_URL
    expose:
      - $KRAKEN_SERVER_PORT
    ports:
      - $KRAKEN_SERVER_PORT:$KRAKEN_SERVER_PORT
    deploy:
      replicas: 2

  # scheduler:
  #   restart: always
  #   image: eu.gcr.io/kraken-261806/kkscheduler:kk_ver
  #   environment:
  #     - KRAKEN_REDIS_ADDR
  #     - KRAKEN_DB_URL
  #     - KRAKEN_LOGSTASH_PORT
  #     - KRAKEN_LOGSTASH_ADDR
  #     - KRAKEN_ELASTICSEARCH_PORT
  #     - KRAKEN_ELASTICSEARCH_URL
  #     - KRAKEN_SERVER_PORT
  #     - KRAKEN_SERVER_ADDR
  #     - KRAKEN_PLANNER_URL

  # planner:
  #   restart: always
  #   image: eu.gcr.io/kraken-261806/kkplanner:kk_ver
  #   environment:
  #     - KRAKEN_REDIS_ADDR
  #     - KRAKEN_DB_URL
  #     - KRAKEN_LOGSTASH_PORT
  #     - KRAKEN_LOGSTASH_ADDR
  #     - KRAKEN_ELASTICSEARCH_PORT
  #     - KRAKEN_ELASTICSEARCH_URL
  #     - KRAKEN_SERVER_PORT
  #     - KRAKEN_SERVER_ADDR
  #     - KRAKEN_PLANNER_URL

  controller:
    restart: always
    image: eu.gcr.io/kraken-261806/kkcontroller:kk_ver
    environment:
      - KRAKEN_REDIS_ADDR
      - KRAKEN_DB_URL
      - KRAKEN_LOGSTASH_PORT
      - KRAKEN_LOGSTASH_ADDR
      - KRAKEN_ELASTICSEARCH_PORT
      - KRAKEN_ELASTICSEARCH_URL
      - KRAKEN_SERVER_PORT
      - KRAKEN_SERVER_ADDR
      - KRAKEN_PLANNER_URL

  celery:
    restart: always
    image: eu.gcr.io/kraken-261806/kkcelery:kk_ver
    environment:
      - KRAKEN_REDIS_ADDR
      - KRAKEN_DB_URL
      - KRAKEN_LOGSTASH_PORT
      - KRAKEN_LOGSTASH_ADDR
      - KRAKEN_ELASTICSEARCH_PORT
      - KRAKEN_ELASTICSEARCH_URL
      - KRAKEN_SERVER_PORT
      - KRAKEN_SERVER_ADDR
      - KRAKEN_PLANNER_URL

  agent:
    restart: always
    image: eu.gcr.io/kraken-261806/kkagent:kk_ver
    environment:
      - KRAKEN_REDIS_ADDR
      - KRAKEN_DB_URL
      - KRAKEN_LOGSTASH_PORT
      - KRAKEN_LOGSTASH_ADDR
      - KRAKEN_ELASTICSEARCH_PORT
      - KRAKEN_ELASTICSEARCH_URL
      - KRAKEN_SERVER_PORT
      - KRAKEN_SERVER_ADDR
      - KRAKEN_AGENT_SLOT={{.Task.Slot}}
    deploy:
      replicas: 3

  ui:
    image: eu.gcr.io/kraken-261806/kkui:kk_ver
    environment:
      - KRAKEN_REDIS_ADDR
      - KRAKEN_DB_URL
      - KRAKEN_LOGSTASH_PORT
      - KRAKEN_LOGSTASH_ADDR
      - KRAKEN_ELASTICSEARCH_PORT
      - KRAKEN_ELASTICSEARCH_URL
      - KRAKEN_SERVER_PORT
      - KRAKEN_SERVER_ADDR
    ports:
      - "8080:80"

  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

# ELK
  elasticsearch:
    image: elasticsearch:7.5.0
    environment:
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      cluster.name: kraken-cluster
      network.host: 0.0.0.0
      discovery.type: single-node
    # ulimits:
    #   memlock: -1
    #   nofile:
    #     hard: 65536
    #     soft: 65536
    #   nproc: 65538
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
#    ports:
#      - "9200:9200"
#      - "9300:9300"

  logstash:
    image: logstash:7.5.0
    command: sh -c "logstash -e 'input { udp { codec => json port => 5959 } } output { elasticsearch { codec => json hosts => \"elasticsearch:9200\" user => \"elastic\" password => \"changeme\" } }'"
    ports:
      - $KRAKEN_LOGSTASH_PORT:$KRAKEN_LOGSTASH_PORT/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    image: kibana:7.5.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: $KRAKEN_ELASTICSEARCH_URL
    ports:
      - "5601:5601"



volumes:
  db-data:
  elasticsearch:
