version: '3'

services:
  server:
    restart: always
    build:
      context: kraken
      dockerfile: docker-server.txt
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - db_net
      - web_net
      - lab_net
    environment:
      DB_URL: "postgresql://kraken:kk123@postgres:5432/kraken"
    depends_on:
      - postgres

  scheduler:
    restart: always
    build:
      context: kraken
      dockerfile: docker-scheduler.txt
    networks:
      - db_net
    environment:
      DB_URL: "postgresql://kraken:kk123@postgres:5432/kraken"
    depends_on:
      - postgres

  agent:
    restart: always
    build:
      context: kraken
      dockerfile: docker-agent.txt
    networks:
      - lab_net
    environment:
      SERVER: "server"
    depends_on:
      - server

  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - web_net
    environment:
      API_HOST: server
      API_PORT: 5000
    depends_on:
      - server

  postgres:
    image: postgres:11
    networks:
      - db_net
    environment:
      POSTGRES_USER: kraken
      POSTGRES_PASSWORD: kk123
      POSTGRES_DB: kraken

  redis:
    image: "redis:alpine"
    networks:
      - db_net

volumes:
  db-data:
  web-data:

networks:
  db_net:
    driver: bridge
  web_net:
    driver: bridge
  lab_net:
    driver: bridge
