apiVersion: v1
kind: Service
metadata:
  labels:
    kraken.service: clickhouse
  name: clickhouse
spec:
  ports:
    - name: "8123"
      port: 8123
      targetPort: http
    - name: "9000"
      port: 9000
      targetPort: ch
  selector:
    kraken.service: clickhouse
