apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    kraken.service: clickhouse
  name: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
