apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: kraken-crb

roleRef:
  kind: ClusterRole
  name: kraken-role
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: kraken
    namespace: {{ .Release.Namespace }}