apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kraken.service: controller
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      kraken.service: controller
  template:
    metadata:
      labels:
        kraken.service: controller
    spec:
      containers:
        - name: controller
          env:
            - name: KRAKEN_CLICKHOUSE_ADDR
              value: clickhouse-proxy:9001
            - name: KRAKEN_CLICKHOUSE_PORT
              value: "9001"
            - name: KRAKEN_CLICKHOUSE_URL
              value: http://clickhouse:8123/
            - name: KRAKEN_DB_URL
              value: postgresql://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@postgres:5432/{{ .Values.postgresql.db }}
            - name: KRAKEN_PLANNER_URL
              value: http://localhost:7997/
            - name: KRAKEN_REDIS_ADDR
              value: redis
            - name: KRAKEN_SERVER_ADDR
              value: server:6363
            - name: KRAKEN_SERVER_PORT
              value: "6363"
          image: {{ .Values.image.baseUrl }}/kkcontroller:{{ .Chart.AppVersion }}
          ports:
            - name: planner
              containerPort: 7997
      restartPolicy: Always
      serviceAccountName: kraken