apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kraken.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      kraken.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        kraken.service: minio
    spec:
      containers:
        - args:
            - server
            - --address
            - :9999
            - /data
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.root_user }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.root_password }}
          image: minio/minio:RELEASE.2022-10-24T18-35-07Z
          name: minio
          ports:
            - name: minio
              containerPort: 9999
          volumeMounts:
            - mountPath: /data
              name: minio
      restartPolicy: Always
      volumes:
        - name: minio
          persistentVolumeClaim:
            claimName: minio
