"""unique constraints on branch name and project

Revision ID: 87c9aa977ded
Revises: 42ea01a6cf31
Create Date: 2021-06-27 15:44:06.585070

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '87c9aa977ded'
down_revision = '42ea01a6cf31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_branch_branch_name_project_id', 'branches', ['branch_name', 'project_id'])
    op.create_unique_constraint('uq_branch_name_project_id', 'branches', ['name', 'project_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_branch_name_project_id', 'branches', type_='unique')
    op.drop_constraint('uq_branch_branch_name_project_id', 'branches', type_='unique')
    # ### end Alembic commands ###
